version: "3"

services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Admin#123
    networks:
      - mysql_network
  python-application:
    restart: always
    image: pythonapp:v1
    container_name: python-application
    ports:
      - 5000:5000
    depends_on:
      - mysqldb
    networks:
      - mysql_network

volumes:
    db_data: {}

networks:
  mysql_network:
